import { test, expect } from '../../fixtures';
import { GUEST_PAGES, PATHS, dismissPopups } from '../../helpers/openstudio';

// Baselines are generated by the USER on first live run (`--update-snapshots`).
test.describe('Guest · public pages [WooCommerce][OS theme]', () => {
  for (const [slug, path] of GUEST_PAGES) {
    test(`OS-GUEST-${slug}`, async ({ shopperPage }) => {
      await shopperPage.goto(path, { waitUntil: 'networkidle' });
      await dismissPopups(shopperPage);
      await expect(shopperPage).toHaveScreenshot(`${slug}.png`, { fullPage: true });
    });
  }

  test('OS-GUEST-menu-desktop', async ({ shopperPage }) => {
    await shopperPage.goto(PATHS.home, { waitUntil: 'networkidle' });
    await dismissPopups(shopperPage);
    await expect(shopperPage.locator('header').first()).toBeVisible();
    await expect(shopperPage.locator('header').first()).toHaveScreenshot('menu-desktop.png');
  });

  test('OS-GUEST-menu-mobile', async ({ shopperPage }) => {
    await shopperPage.setViewportSize({ width: 390, height: 844 });
    await shopperPage.goto(PATHS.home, { waitUntil: 'networkidle' });
    await dismissPopups(shopperPage);
    await expect(shopperPage.locator('header').first()).toHaveScreenshot('menu-mobile.png');
  });
});
